"use client";

import { useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { useTheme } from "@/app/context/ThemeContext";
import type { User } from "@supabase/supabase-js";

interface Baby {
  id: string;
  name: string;
  birth_date: string;
  gender: string | null;
}

interface SettingsContentProps {
  user: User;
  babies: Baby[];
}

export default function SettingsContent({ user, babies }: SettingsContentProps) {
  const [exporting, setExporting] = useState(false);
  const router = useRouter();
  const supabase = createClient();
  const { theme, toggleTheme } = useTheme();

  const handleSignOut = async () => {
    await supabase.auth.signOut();
    router.push("/");
    router.refresh();
  };

  const handleExportPDF = async () => {
    setExporting(true);
    try {
      // Dynamically import jspdf
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF();
      
      // Title
      doc.setFontSize(22);
      doc.setTextColor(66, 90, 81); // #425a51
      doc.text("Bobo Baby Data Export", 20, 25);
      
      doc.setFontSize(10);
      doc.setTextColor(128, 128, 128);
      doc.text(`Generated on ${new Date().toLocaleDateString()}`, 20, 32);
      
      let yPos = 50;
      
      // User info
      doc.setFontSize(14);
      doc.setTextColor(0, 0, 0);
      doc.text("Account Information", 20, yPos);
      yPos += 10;
      
      doc.setFontSize(11);
      doc.text(`Email: ${user.email}`, 25, yPos);
      yPos += 7;
      doc.text(`Account Created: ${new Date(user.created_at).toLocaleDateString()}`, 25, yPos);
      yPos += 15;
      
      // Babies
      if (babies.length > 0) {
        doc.setFontSize(14);
        doc.text("Baby Profiles", 20, yPos);
        yPos += 10;
        
        for (const baby of babies) {
          const age = Math.floor((Date.now() - new Date(baby.birth_date).getTime()) / (1000 * 60 * 60 * 24 * 30.44));
          doc.setFontSize(11);
          doc.text(`• ${baby.name}`, 25, yPos);
          yPos += 6;
          doc.setFontSize(10);
          doc.setTextColor(100, 100, 100);
          doc.text(`  Born: ${new Date(baby.birth_date).toLocaleDateString()} (${age} months old)`, 25, yPos);
          doc.setTextColor(0, 0, 0);
          yPos += 6;
          doc.text(`  Gender: ${baby.gender || "Not specified"}`, 25, yPos);
          yPos += 10;
          
          // Fetch logs for this baby
          const { data: sleepLogs } = await supabase
            .from("sleep_logs")
            .select("*")
            .eq("baby_id", baby.id)
            .order("start_time", { ascending: false })
            .limit(10);
          
          const { data: feedingLogs } = await supabase
            .from("feeding_logs")
            .select("*")
            .eq("baby_id", baby.id)
            .order("start_time", { ascending: false })
            .limit(10);
          
          const { data: diaperLogs } = await supabase
            .from("diaper_logs")
            .select("*")
            .eq("baby_id", baby.id)
            .order("logged_at", { ascending: false })
            .limit(10);
          
          // Summary
          doc.setFontSize(10);
          doc.text(`  Recent Activity: ${sleepLogs?.length || 0} sleep, ${feedingLogs?.length || 0} feeding, ${diaperLogs?.length || 0} diaper logs`, 25, yPos);
          yPos += 15;
          
          if (yPos > 270) {
            doc.addPage();
            yPos = 20;
          }
        }
      } else {
        doc.setFontSize(11);
        doc.text("No baby profiles yet", 25, yPos);
        yPos += 15;
      }
      
      // Footer
      doc.setFontSize(9);
      doc.setTextColor(150, 150, 150);
      doc.text("Generated by Bobo - Smart Baby Tracking", 20, 285);
      
      // Save
      doc.save(`bobo-export-${new Date().toISOString().split("T")[0]}.pdf`);
    } catch (error) {
      console.error("PDF export error:", error);
      alert("Failed to export PDF. Please try again.");
    }
    setExporting(false);
  };

  const userName = user.user_metadata?.full_name || user.email?.split("@")[0] || "Parent";

  return (
    <div className="min-h-screen bg-[#fafafa] dark:bg-gray-900 transition-colors">
      {/* Header */}
      <header className="bg-white dark:bg-gray-800 border-b border-gray-100 dark:border-gray-700 sticky top-0 z-50">
        <div className="max-w-3xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link href="/dashboard" className="flex items-center gap-2 text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-white transition-colors">
            <span className="text-xl">←</span>
            <span className="font-medium">Dashboard</span>
          </Link>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-3xl mx-auto px-6 py-8">
        <h1 className="text-3xl font-bold text-gray-900 dark:text-white mb-8">⚙️ Settings</h1>

        {/* Profile Section */}
        <div className="bg-white dark:bg-gray-800 rounded-2xl p-6 border border-gray-100 dark:border-gray-700 mb-6">
          <h2 className="text-lg font-bold text-gray-900 dark:text-white mb-4">Profile</h2>
          <div className="flex items-center gap-4 mb-6">
            <div className="w-16 h-16 rounded-full bg-[#425a51] text-white flex items-center justify-center text-2xl font-bold">
              {userName.charAt(0).toUpperCase()}
            </div>
            <div>
              <p className="font-bold text-gray-900 dark:text-white">{userName}</p>
              <p className="text-sm text-gray-500 dark:text-gray-400">{user.email}</p>
            </div>
          </div>
          <div className="space-y-3">
            <div className="flex justify-between items-center py-3 border-b border-gray-100 dark:border-gray-700">
              <span className="text-gray-600 dark:text-gray-400">Email</span>
              <span className="text-gray-900 dark:text-white">{user.email}</span>
            </div>
            <div className="flex justify-between items-center py-3 border-b border-gray-100 dark:border-gray-700">
              <span className="text-gray-600 dark:text-gray-400">Account Created</span>
              <span className="text-gray-900 dark:text-white">
                {new Date(user.created_at).toLocaleDateString()}
              </span>
            </div>
          </div>
        </div>

        {/* Quick Links */}
        <div className="bg-white dark:bg-gray-800 rounded-2xl p-6 border border-gray-100 dark:border-gray-700 mb-6">
          <h2 className="text-lg font-bold text-gray-900 dark:text-white mb-4">Quick Links</h2>
          <div className="grid grid-cols-2 gap-3">
            <Link href="/dashboard/babies/new" className="p-4 bg-[#f4f6f5] dark:bg-gray-700 rounded-xl text-center hover:bg-[#e8edea] dark:hover:bg-gray-600 transition-colors">
              <div className="text-2xl mb-1">👶</div>
              <span className="text-sm font-medium text-gray-900 dark:text-white">Add Baby</span>
            </Link>
            <Link href="/dashboard/growth" className="p-4 bg-[#f4f6f5] dark:bg-gray-700 rounded-xl text-center hover:bg-[#e8edea] dark:hover:bg-gray-600 transition-colors">
              <div className="text-2xl mb-1">📏</div>
              <span className="text-sm font-medium text-gray-900 dark:text-white">Growth Charts</span>
            </Link>
            <Link href="/dashboard/nutrition" className="p-4 bg-[#f4f6f5] dark:bg-gray-700 rounded-xl text-center hover:bg-[#e8edea] dark:hover:bg-gray-600 transition-colors">
              <div className="text-2xl mb-1">🥗</div>
              <span className="text-sm font-medium text-gray-900 dark:text-white">Nutrition</span>
            </Link>
            <Link href="/dashboard/ai-chat" className="p-4 bg-[#f4f6f5] dark:bg-gray-700 rounded-xl text-center hover:bg-[#e8edea] dark:hover:bg-gray-600 transition-colors">
              <div className="text-2xl mb-1">🤖</div>
              <span className="text-sm font-medium text-gray-900 dark:text-white">AI Chat</span>
            </Link>
          </div>
        </div>

        {/* Preferences */}
        <div className="bg-white dark:bg-gray-800 rounded-2xl p-6 border border-gray-100 dark:border-gray-700 mb-6">
          <h2 className="text-lg font-bold text-gray-900 dark:text-white mb-4">Preferences</h2>
          <div className="space-y-4">
            {/* Dark Mode Toggle - WORKING */}
            <div className="flex items-center justify-between py-3 border-b border-gray-100 dark:border-gray-700">
              <div className="flex items-center gap-3">
                <span className="text-2xl">{theme === "dark" ? "🌙" : "☀️"}</span>
                <div>
                  <span className="text-gray-900 dark:text-white font-medium">
                    {theme === "dark" ? "Dark Mode" : "Light Mode"}
                  </span>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    {theme === "dark" ? "Switch to light theme" : "Switch to dark theme"}
                  </p>
                </div>
              </div>
              <button
                onClick={toggleTheme}
                className={`w-14 h-8 rounded-full relative transition-colors ${
                  theme === "dark" ? "bg-[#425a51]" : "bg-gray-300"
                }`}
              >
                <div
                  className={`absolute top-1 w-6 h-6 bg-white rounded-full shadow-md transition-transform ${
                    theme === "dark" ? "translate-x-7" : "translate-x-1"
                  }`}
                />
              </button>
            </div>

            {/* Notifications - Coming Soon */}
            <div className="flex items-center justify-between py-3 border-b border-gray-100 dark:border-gray-700">
              <div className="flex items-center gap-3">
                <span className="text-2xl">🔔</span>
                <div>
                  <span className="text-gray-900 dark:text-white font-medium">Notifications</span>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Enable push notifications</p>
                </div>
              </div>
              <span className="px-3 py-1 bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-400 text-xs font-medium rounded-full">
                Coming Soon
              </span>
            </div>

            {/* Export Data - WORKING */}
            <div className="flex items-center justify-between py-3">
              <div className="flex items-center gap-3">
                <span className="text-2xl">📤</span>
                <div>
                  <span className="text-gray-900 dark:text-white font-medium">Export Data</span>
                  <p className="text-sm text-gray-500 dark:text-gray-400">Download your data as PDF</p>
                </div>
              </div>
              <button
                onClick={handleExportPDF}
                disabled={exporting}
                className="px-4 py-2 bg-[#425a51] text-white text-sm font-medium rounded-xl hover:bg-[#364842] transition-colors disabled:opacity-50"
              >
                {exporting ? "Exporting..." : "Export PDF"}
              </button>
            </div>
          </div>
        </div>

        {/* App Info */}
        <div className="bg-white dark:bg-gray-800 rounded-2xl p-6 border border-gray-100 dark:border-gray-700 mb-6">
          <h2 className="text-lg font-bold text-gray-900 dark:text-white mb-4">About</h2>
          <div className="space-y-3 text-sm">
            <div className="flex justify-between items-center py-2">
              <span className="text-gray-600 dark:text-gray-400">Version</span>
              <span className="text-gray-900 dark:text-white">2.0.0</span>
            </div>
            <div className="flex justify-between items-center py-2">
              <span className="text-gray-600 dark:text-gray-400">Support</span>
              <a href="mailto:support@bobo.app" className="text-[#425a51] dark:text-[#6b9c8c] hover:underline">support@bobo.app</a>
            </div>
          </div>
        </div>

        {/* Danger Zone */}
        <div className="bg-red-50 dark:bg-red-900/20 rounded-2xl p-6 border border-red-100 dark:border-red-900/50">
          <h2 className="text-lg font-bold text-red-800 dark:text-red-400 mb-4">Account Actions</h2>
          <button
            onClick={handleSignOut}
            className="w-full py-3 rounded-xl bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400 font-medium hover:bg-red-200 dark:hover:bg-red-900/50 transition-colors"
          >
            Sign Out
          </button>
        </div>
      </main>
    </div>
  );
}
